# File              : config.yml
# Author            : Marcos Horro <marcos.horro@udc.gal>
# Date              : MÃ©r 06 Nov 2019 16:36:12 MST
# Last Modified Date: Mar 12 Nov 2019 10:52:47 MST
# Last Modified By  : Marcos Horro <marcos.horro@udc.gal>
#
# example file, this file should be used for executing with wrapper.py
# POSSIBLE VALUES
#- general:
#    input: # existing valid filename
#    output: # valid filename
#    overwrite: # True/False
#    clean: # True/False, for cleaning temp files
#    debug: # True/False, for printing debug outputs
#- prepare_data:
#    cols: # columns to use for DT
#    rows: # filtering rows in CSV
#    pred: # dimension to predict
#    norm: # norm values
#    norm_alg: # z-score/minmax; useless if norm: False
#    ncats: # use 0 for discrete values, value greater than 1 in other case
#    dt_alg: # REPTree or J48 right now (tested)
#    dt_params: # e.g. M 5 N 1 (minimum 5 instances, 1 fold), or ''
#- recommender:
#    interest_value: # value of interest of prediction
#    interest_value_type: # numeric/nominal (categorial also called)
#    dimension: # dimensions we want to know, analogous value == cols in
#                 prepare_data

- general:
    input: test_data/exec_asm_full_filtered.csv
    output: output.arff
    overwrite: True # overwrite if existing files?
    clean: True # clean temp files?
    debug: True
- prepare_data:
    cols: I J It Jt Is Js Jters Iters NELEMS
    rows: I=0 J=0 Vec_x=1
    pred: FLOPSs # dimension to predict
    norm: False # norm values
    norm_alg: None # z-score/minmax; useless if norm: False
    ncats: 10 # use 0 for discrete values
    dt_alg: J48
    dt_params: ''
    min_acc: 0.8 # minimum accuracy accepted of DT
- recommender:
    interest_value: 6.5
    interest_value_type: numeric # numeric/nominal
    dimensions: I J It Jt Is Js
